### ISSUE TITLE
addon won't load

### ISSUE THREAD

**Issue by allenwilson** [tosimplicity/AnkiRelateToMyDoc#4]
This is exactly the kind of thing I've wanted Anki to be able to do for years now! Thank you so much for making it. 
I'm having trouble getting the add on to load. 
I'm running Anki 2.1 on mac. 
After adding the add on and restarting Anki, I get this message:

When loading 'Anki Relate To My Doc':
Traceback (most recent call last):
   File "aqt/addons.py", line 60, in
loadAddons
 File "/Users/allenwilson/Library/Application Support/Anki2/addons21/143084803/_init_.py", line 31,
in <module>
   from .logging_handlers import
TimeRotatingFileHandlerModuleNotFoundError: No module named "143084803.logging_handlers'

**Comment by tosimplicity** [comment]
Please check if logging_handlers.py exists in /Users/allenwilson/Library/Application Support/Anki2/addons21/143084803/logging_handlers.py. If not, would you please try to re-install the add-on. Sorry for response this late.
